# Use new infrastructure
sudo: false

language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - ./ci/setup_codesniffer.sh

script:
    # Search for PHP syntax errors.
    - find . -name "*.php" -exec php -lf {} \;
    # Check against WordPress Coding Standards
    # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
    # @link http://pear.php.net/package/PHP_CodeSniffer/
    # -p flag: Show progress of the run.
    # -s flag: Show sniff codes in all reports.
    # -v flag: Print verbose output.
    # -n flag: Do not print warnings (shortcut for --warning-severity=0)
    # --standard: Use WordPress as the standard.
    # --extensions: Only sniff PHP files.
    - /tmp/wordpress/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php